version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14.2-bullseye
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432
